### ISSUE TITLE
What the virus do? For android

### ISSUE THREAD

**Issue by cristiandonaraDEV** [mishakorzik/Infect#1]

**Comment by mishakorzik** [comment]
the virus fills the device's memory, and the device starts to bug, and then the device does not start.

**Comment by MagevaCodes** [comment]
Is there a possible way the application supposed to be downloaded can be changed the name to fit my needs?

**Comment by mishakorzik** [comment]
No

**Comment by Mrhssjsh** [comment]
Hello mish

**Comment by mishakorzik** [comment]
Hi

**Comment by moondhop** [comment]
Infect ko use kaise karye
